# ==============================================================================
# HAOS Linux - Security Limits
# Abertura de sockets, limites de processos e arquivos simultâneos
# ==============================================================================

haos            soft    nofile          65535
haos            hard    nofile          1048576
haos            soft    nproc           32768
haos            hard    nproc           65535
haos            soft    memlock         unlimited
haos            hard    memlock         unlimited

root            soft    nofile          65535
root            hard    nofile          1048576
root            soft    nproc           32768
root            hard    nproc           65535
root            soft    memlock         unlimited
root            hard    memlock         unlimited

*               soft    nofile          65535
*               hard    nofile          1048576
