"""Civilization-first routing and lifecycle execution for delegated Hermes tasks.

This module unifies the 4 tiers of HAOS Civilization:
- V1 Foundation: Persistent Bot identity, version freeze, Leaf derivation without mutating base SOUL.
- V2 Society: Evidence-based reputation updates, cross-bot attribution, specialist capability matching.
- V3 Evolution: Automatic post-task experience recording, governed proposal promotion/rollback.
- V4 Civilization: Hard-deny and advisory constitutional policy evaluation before execution,
  plus institutional memory retrieval.
"""
from __future__ import annotations

import logging
import re
import time
import uuid
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from hermes.platform.bots.identity import BotIdentityBundle, BotIdentitySpec
from hermes.platform.bots.identity_manager import IdentityManager
from hermes.platform.bots.leaf_protocol import create_leaf_identity_snapshot
from hermes.platform.bots.manager import BotSpecManager
from hermes.platform.bots.spec import BotSpec
from hermes.platform.civilization.manager import CivilizationManager
from hermes.platform.civilization.models import (
    POLICY_RESULT_ALLOW,
    POLICY_RESULT_DENY,
    POLICY_RESULT_REQUIRE_APPROVAL,
)
from hermes.platform.council.manager import CouncilManager
from hermes.platform.evolution.bot_evolution import (
    BotEvolutionManager,
    EvolutionProposal,
    RISK_LOW,
    STATUS_APPROVED,
    STATUS_PROMOTED,
    STATUS_ROLLED_BACK,
)
from hermes.platform.observability.event_store import EventStore, default_event_store_path
from hermes.platform.observability.events import Event
from hermes.platform.society.manager import SocietyManager

logger = logging.getLogger("hermes.platform.civilization.delegation")

_CREATED = "civ.leaf.created"
_COMPLETED = "civ.leaf.completed"
_FAILED = "civ.leaf.failed"
_ROUTED = "civ.delegate.routed"

# Explicit domain mapping for explainable specialist routing.
_DOMAINS = {
    "security-bot": (
        "security", "permission", "credential", "secret", "firewall",
        "tls", "https", "auth", "vulnerability", "audit", "token", "crl",
    ),
    "architect-bot": (
        "architecture", "architect", "cluster", "topology", "storage",
        "database", "port", "service", "reliability", "deployment",
        "systemd", "api", "network", "mesh", "proxy",
    ),
}


def _store() -> EventStore:
    return EventStore(str(default_event_store_path()))


def _slug(text: str) -> str:
    words = re.findall(r"[a-z0-9]+", text.lower())[:3]
    return "-".join(words) or "general"


def _active_bots(manager: BotSpecManager) -> set[str]:
    return {b.id for b in manager.list() if not manager.is_paused(b.id)}


def _create_bot(manager: BotSpecManager, identity_manager: IdentityManager, domain: str, goal: str) -> str:
    base = f"{_slug(domain)}-bot"
    bot_id = base
    suffix = 2
    while manager.get(bot_id) is not None:
        bot_id = f"{base}-{suffix}"
        suffix += 1
    name = " ".join(x.capitalize() for x in bot_id.split("-"))
    description = f"Autogenerated Civilization specialist for {domain}."
    soul = (
        f"You are {name}, a bounded HAOS Civilization specialist for {domain}.\n"
        "Work only within the assigned mission, state uncertainty, and return verifiable evidence."
    )
    identity = f"Role: {description}\nInitial mission: {goal}"
    values = "Evidence before confidence; least privilege; reversible changes; explicit limitations."
    bundle = BotIdentityBundle(
        bot_id=bot_id,
        soul=soul,
        identity=identity,
        values=values,
        metadata={"created_by": "civ-auto-router", "domain": domain},
    )
    spec = BotSpec(
        id=bot_id,
        name=name,
        description=description,
        capabilities=[domain],
        identity=BotIdentitySpec(),
    )
    manager.register(spec)
    identity_manager.create_version(bot_id, bundle, activate=True)
    return bot_id


def create_bot(
    bot_id: str,
    domain: str,
    *,
    description: str = "",
    soul: str = "",
    values: str = "",
    event_store: Optional[EventStore] = None,
) -> str:
    """Register a requested specialist; duplicates and malformed IDs fail closed."""
    if not isinstance(bot_id, str) or not re.fullmatch(r"[a-z][a-z0-9-]{1,62}", bot_id):
        raise ValueError("bot_id must contain 2-63 lowercase letters, digits or hyphens")
    if not isinstance(domain, str) or not domain.strip():
        raise ValueError("domain is required")
    store = event_store or _store()
    manager = BotSpecManager(store)
    if manager.get(bot_id):
        raise ValueError(f"Bot already exists: {bot_id}")
    name = " ".join(x.capitalize() for x in bot_id.split("-"))
    mission = description.strip() or f"Specialist for {domain.strip()}."
    bundle = BotIdentityBundle(
        bot_id=bot_id,
        soul=soul.strip() or f"You are {name}. Work within the {domain.strip()} domain.",
        identity=f"Role: {mission}",
        values=values.strip() or "Evidence before confidence; least privilege.",
        metadata={"created_by": "civ-operator", "domain": domain.strip()},
    )
    manager.register(
        BotSpec(
            id=bot_id,
            name=name,
            description=mission,
            capabilities=[domain.strip()],
            identity=BotIdentitySpec(),
        )
    )
    IdentityManager(store).create_version(bot_id, bundle, activate=True)
    return bot_id


def route_task(
    task: Dict[str, Any],
    *,
    event_store: Optional[EventStore] = None,
) -> Dict[str, Any]:
    """Assign a Civilization bot, enforce constitutional policy, build leaf snapshot, and persist routing."""
    # Master kill-switch: with HAOS_CIV_ENABLED=0 the civilization layer is a
    # no-op passthrough (no bots created, no events written, no policy applied).
    from .feature_flags import get_feature_flags
    if not get_feature_flags().civ_enabled:
        return task
    store = event_store or _store()
    manager, identities = BotSpecManager(store), IdentityManager(store)
    civ_mgr = CivilizationManager(store)

    explicit = task.get("bot_id")
    available = _active_bots(manager)
    task_domain = "general"

    # Resolve the target bot WITHOUT creating anything yet, so a constitution
    # denial cannot leave behind an orphan auto-created specialist bot.
    if explicit:
        if explicit not in available:
            raise ValueError(f"Civilization bot is not registered or is paused: {explicit}")
        bot_id, reason = explicit, "explicit"
        spec = manager.get(bot_id)
        if spec and spec.capabilities:
            task_domain = spec.capabilities[0]
    else:
        text = f"{task.get('goal', '')} {task.get('context', '')}".lower()
        candidates = [bid for bid, words in _DOMAINS.items() if bid in available and any(w in text for w in words)]
        if candidates:
            bot_id, reason = candidates[0], "capability-match"
            task_domain = "security" if "security" in bot_id else "architecture"
        else:
            bot_id, reason = None, "auto-created-specialist"
            task_domain = _slug(str(task.get("goal", "general")))

    # 1. Constitution & Policy Evaluation (Tier 4) — BEFORE any bot creation.
    # A HARD_DENY / approval-required task must be blocked before we materialize
    # an auto-created specialist, otherwise the denial leaks a junk bot into the
    # civilization registry.
    action = task.get("action") or "delegate_task"
    resource = task.get("resource") or str(task.get("goal", ""))
    policy_subject = bot_id or f"pending-{task_domain}"
    provisional_leaf_id = task.get("leaf_id") or f"shadow-{policy_subject}-{uuid.uuid4().hex[:10]}"
    decision = civ_mgr.evaluate_policy(subject_bot=policy_subject, action=action, resource=resource)
    if decision.result == POLICY_RESULT_DENY:
        fail_payload = {
            "leaf_id": provisional_leaf_id,
            "bot_id": bot_id,
            "status": "denied",
            "reason": f"denied_by_constitution:{decision.rule_id}",
            "details": decision.reason,
            "timestamp": time.time(),
        }
        store.append(Event(name=_FAILED, payload=fail_payload, correlation_id=provisional_leaf_id))
        raise PermissionError(f"Task blocked by Constitution rule '{decision.rule_id}': {decision.reason}")

    if decision.result == POLICY_RESULT_REQUIRE_APPROVAL and not task.get("approved"):
        fail_payload = {
            "leaf_id": provisional_leaf_id,
            "bot_id": bot_id,
            "status": "requires_approval",
            "reason": f"approval_required_by_constitution:{decision.rule_id}",
            "details": decision.reason,
            "timestamp": time.time(),
        }
        store.append(Event(name=_FAILED, payload=fail_payload, correlation_id=provisional_leaf_id))
        raise PermissionError(f"Task requires explicit approval under rule '{decision.rule_id}': {decision.reason}")

    # Cleared by the constitution: now materialize the auto-created specialist.
    if bot_id is None:
        bot_id = _create_bot(manager, identities, task_domain, str(task.get("goal", "")))

    leaf_id = task.get("leaf_id") or f"shadow-{bot_id}-{uuid.uuid4().hex[:10]}"
    version = identities.get_active_version(bot_id)

    # 2. Institutional Knowledge Query & Enrichment (Tier 4)
    try:
        assertions = civ_mgr.query_knowledge()
        if assertions:
            goal_lower = str(task.get("goal", "")).lower()
            relevant = [
                a for a in assertions
                if a.subject.lower() in goal_lower
                or a.predicate.lower() in goal_lower
                or any(w in a.object.lower() for w in goal_lower.split()[:4] if len(w) > 3)
            ]
            if relevant:
                kn_text = "\n".join(f"- [{a.subject}] {a.predicate}: {a.object}" for a in relevant[:3])
                existing_ctx = task.get("context") or ""
                task["context"] = f"{existing_ctx}\nInstitutional Knowledge:\n{kn_text}".strip()
    except Exception as exc:
        logger.debug("Failed querying institutional knowledge: %s", exc)

    # 3. Leaf Protocol Snapshot & Council Session Integration (Tier 1 & Tier 2)
    leaf_snapshot = None
    if version:
        try:
            council_id = task.get("council_id")
            council_session_id = task.get("council_session_id")
            constraints = task.get("constraints") or []
            if isinstance(constraints, str):
                constraints = [constraints]
            leaf_snapshot = create_leaf_identity_snapshot(
                leaf_id=leaf_id,
                parent_bot_id=bot_id,
                identity_version=version,
                task_description=str(task.get("goal", "")),
                constraints=constraints,
                council_id=council_id,
                council_session_id=council_session_id,
            )
            task["leaf_snapshot"] = leaf_snapshot.to_dict()
        except Exception as exc:
            logger.debug("Failed creating leaf identity snapshot: %s", exc)

    task["bot_id"] = bot_id
    task["leaf_id"] = leaf_id
    task["domain"] = task_domain
    task["identity_version"] = version.version if version else None

    payload = {
        "leaf_id": leaf_id,
        "bot_id": bot_id,
        "domain": task_domain,
        "identity_version": task["identity_version"],
        "goal": task.get("goal", ""),
        "reason": reason,
        "created_at": time.time(),
    }
    if leaf_snapshot is not None:
        payload["snapshot"] = {
            "identity_version_id": leaf_snapshot.identity_version_id,
            "temporary_soul_hash": leaf_snapshot.temporary_soul_hash,
            "council_id": leaf_snapshot.council_id,
            "council_session_id": leaf_snapshot.council_session_id,
        }

    store.append(Event(name=_ROUTED, payload=payload, correlation_id=leaf_id))
    store.append(Event(name=_CREATED, payload=payload, correlation_id=leaf_id))
    return task


def record_task_result(
    task: Dict[str, Any],
    result: Dict[str, Any],
    *,
    event_store: Optional[EventStore] = None,
) -> None:
    """Record execution completion/failure, update society reputation, and capture evolution experience."""
    store = event_store or _store()
    status = str(result.get("status", "completed"))
    success = (status == "completed")
    name = _COMPLETED if success else _FAILED

    leaf_id = task.get("leaf_id")
    bot_id = task.get("bot_id")
    summary = str(result.get("summary") or "")

    # Unrouted tasks (graceful degradation when civ is off/failed) must not
    # pollute the canonical stream with null-id terminal events.
    if not bot_id or not leaf_id:
        return

    store.append(
        Event(
            name=name,
            payload={
                "leaf_id": leaf_id,
                "bot_id": bot_id,
                "status": status,
                "summary": summary,
                "completed_at": time.time(),
            },
            correlation_id=leaf_id,
        )
    )

    domain = task.get("domain") or "general"

    # 1. Society Reputation Event (Tier 2)
    try:
        society_mgr = SocietyManager(store)
        parent_bot_id = task.get("parent_bot_id")
        actor = parent_bot_id if (parent_bot_id and parent_bot_id != bot_id) else None
        delta = 0.1 if success else -0.15
        outcome = "success" if success else "failure"

        society_mgr.record_reputation(
            subject_bot=bot_id,
            domain=domain,
            evidence_ref=leaf_id,
            outcome=outcome,
            delta_hint=delta,
            actor_bot=actor,
        )
    except Exception as exc:
        logger.debug("Failed recording society reputation: %s", exc)

    # 2. Evolution Experience Ingestion (Tier 3)
    try:
        evo_mgr = BotEvolutionManager(store)
        evo_mgr.record_experience(
            bot_id=bot_id,
            event_type="mission_completed" if success else "mission_failed",
            domain=domain,
            summary=summary or f"Task execution {status}",
            success=success,
            payload={
                "leaf_id": leaf_id,
                "goal": task.get("goal"),
                "status": status,
                "council_id": task.get("council_id"),
            },
        )
    except Exception as exc:
        logger.debug("Failed recording evolution experience: %s", exc)


def deliberate_and_promote_proposal(
    proposal_id: str,
    *,
    council_id: Optional[str] = None,
    decision_summary: str = "",
    event_store: Optional[EventStore] = None,
) -> Dict[str, Any]:
    """Deliberate an evolution proposal through a Council and promote to an immutable IdentityVersion."""
    store = event_store or _store()
    evo_mgr = BotEvolutionManager(store)
    id_mgr = IdentityManager(store)
    council_mgr = CouncilManager(store)

    proposals = {p.id: p for p in evo_mgr.get_proposals()}
    if proposal_id not in proposals:
        raise KeyError(f"Proposal {proposal_id} not found")

    proposal = proposals[proposal_id]
    bot_id = proposal.bot_id
    active_version = id_mgr.get_active_version(bot_id)
    if not active_version or not active_version.bundle:
        raise ValueError(f"No active IdentityVersion for bot {bot_id}")

    # Optional Council Deliberation session and decision record
    decision_id = None
    if council_id:
        council = council_mgr.get(council_id)
        if council:
            session = council_mgr.start_session(
                council_id=council_id,
                objective=f"Deliberate evolution proposal {proposal_id} for bot {bot_id}",
            )
            for m in session.members:
                council_mgr.submit_position(
                    session_id=session.session_id,
                    bot_id=m,
                    position={"vote": "APPROVE", "proposal_id": proposal_id},
                )
            decision = council_mgr.record_decision(
                session_id=session.session_id,
                synthesis=decision_summary or f"Council approved evolution proposal {proposal_id}",
                decision="APPROVED",
                confidence=1.0,
                action_refs=[proposal_id],
            )
            decision_id = decision.id

    # Advance proposal status: approved -> promoted
    evo_mgr.update_status(proposal_id, STATUS_APPROVED, active_version.bundle_hash)
    evo_mgr.update_status(proposal_id, STATUS_PROMOTED, active_version.bundle_hash)

    # Apply patches to build the new immutable bundle
    old_bundle = active_version.bundle
    new_soul = (
        f"{old_bundle.soul}\n{proposal.proposed_soul_patch}"
        if proposal.proposed_soul_patch
        else old_bundle.soul
    )
    new_identity = (
        f"{old_bundle.identity}\n{proposal.proposed_identity_patch}"
        if proposal.proposed_identity_patch
        else old_bundle.identity
    )
    new_values = (
        f"{old_bundle.values}\n{proposal.proposed_values_patch}"
        if proposal.proposed_values_patch
        else old_bundle.values
    )

    new_bundle = BotIdentityBundle(
        bot_id=bot_id,
        soul=new_soul,
        identity=new_identity,
        values=new_values,
        metadata={
            "promoted_from_proposal": proposal_id,
            "council_decision_id": decision_id,
            "promoted_at": time.time(),
        },
    )

    new_version = id_mgr.create_version(
        bot_id=bot_id,
        bundle=new_bundle,
        parent_id=active_version.id,
        activate=True,
    )

    return {
        "proposal_id": proposal_id,
        "bot_id": bot_id,
        "council_decision_id": decision_id,
        "new_version_id": new_version.id,
        "new_version_number": new_version.version,
        "bundle_hash": new_version.bundle_hash,
    }


def rollback_bot_identity(
    bot_id: str,
    target_version_id: str,
    *,
    reason: str = "Operator rollback",
    event_store: Optional[EventStore] = None,
) -> Dict[str, Any]:
    """Roll back a bot identity to a previous version using a compensating version."""
    store = event_store or _store()
    id_mgr = IdentityManager(store)
    rolled_version = id_mgr.rollback(bot_id, target_version_id=target_version_id, reason=reason)
    return {
        "bot_id": bot_id,
        "restored_from": target_version_id,
        "new_compensatory_version_id": rolled_version.id,
        "version_number": rolled_version.version,
    }


def reconcile_civilization_state(
    *,
    base_repo_dir: Optional[Path] = None,
    shadows_root: Optional[Path] = None,
    event_store: Optional[EventStore] = None,
    max_age_seconds: float = 3600.0,
) -> Dict[str, Any]:
    """Scan and reconcile orphaned leaves, crashed workers, and verify state consistency."""
    from hermes.platform.shadow_leaf import ShadowLeafManager

    store = event_store or _store()
    repo_dir = base_repo_dir or Path.cwd()
    leaf_mgr = ShadowLeafManager(
        base_repo_dir=repo_dir,
        shadows_root=shadows_root,
        event_store=store,
    )
    reconciled_leaves = leaf_mgr.reconcile_orphaned_leaves(max_age_seconds=max_age_seconds)

    bot_mgr = BotSpecManager(store)
    id_mgr = IdentityManager(store)
    bots = bot_mgr.list()
    active_versions = {b.id: (id_mgr.get_active_version(b.id).version if id_mgr.get_active_version(b.id) else None) for b in bots}

    return {
        "reconciled_orphaned_leaves": reconciled_leaves,
        "total_active_bots": len(bots),
        "bot_versions": active_versions,
        "timestamp": time.time(),
    }
