pub mod c_abi;
pub mod civilization;
pub mod council_manager;
pub mod crypto;
pub mod event_store;
pub mod evolution;
pub mod identity_manager;
pub mod identity_resolver;
pub mod leaf_protocol;
pub mod models;
pub mod society;
pub mod society_manager;

pub use council_manager::{CouncilError, CouncilManager};
pub use crypto::{compute_bundle_hash, compute_sha256, generate_id, now_timestamp};
pub use event_store::{CivEventStore, EventStoreError};
pub use identity_manager::{IdentityManager, IdentityManagerError};
pub use identity_resolver::{resolve_safe_path, IdentityResolver, ResolverError};
pub use leaf_protocol::{build_temporary_soul, create_leaf_identity_snapshot};
pub use models::*;
pub use society::*;
pub use society_manager::{SocietyError, SocietyManager};
pub use evolution::{EvolutionError, EvolutionManager, EvolutionProposal, ExperienceEvent};
pub use civilization::{CivilizationManager, ConstitutionRule, ConstitutionVersion, KnowledgeAssertion, PolicyDecision};
