#!/bin/sh
# Força o uso do Unbound local mesmo quando o DHCP fornecer servidores DNS externos
make_resolv_conf() {
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    echo "options edns0 trust-ad" >> /etc/resolv.conf
}
