# HAOS Appliance SSH Tuning
Port 22
PermitRootLogin prohibit-password
PasswordAuthentication yes
PubkeyAuthentication yes
TCPKeepAlive yes
ClientAliveInterval 60
ClientAliveCountMax 3
UsePAM yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
